### ISSUE TITLE
Refactor CHeroes UI into a BOS Widget ♻️

### ISSUE THREAD

**Issue by doulos819** [MarmaJFoundation/cryptoheroes#1]
### Pain
Without a BOS implementation, https://pd.marmaj.org/?page=cryptohero is difficult to access for most of the NEAR community.

### What code could be improved?
https://github.com/MarmaJFoundation/cryptoheroes

### Tasks
- [x] Update README for this repo
- [x] Create a widget for CryptoHeroes
- [x] Add some basic functionality to view on chain data from the game

### More Information
This task should be done in phases. An MVP version should simple have some buttons and some on chain data, and a final version should provide all smart contract functionality + big fixes in the BOS UI.

Example of MJG widget: https://near.social/#/shemar268abel.near/widget/MJG-Widget
